server:
  port: 8080
  error:
    include-message: always

spring:
  application:
    name: sb-hexagonal-architecture

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  sql:
    init:
      mode: always

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    org.hibernate.SQL: DEBUG